name: Sync Fork

on:
  schedule:
    # 每天凌晨 2 点 UTC 执行
    - cron: "0 2 * * *"

  # 支持手动执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Sync fork
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.mergeUpstream({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "main"
            })
